### ISSUE TITLE
How do I generate the labeled data?

### ISSUE THREAD

**Issue by luhas123** [pocheyeniu/SummaRuNNer#1]
I get this error when I run "train.py":

`
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    train("model.0201")
  File "train.py", line 55, in train
    dr.load_data(FLAGS.train_data_file, max_doc_length, max_sen_length)
  File "/scratch/user/phan3006/MATH689/SummaRuNNer/data_reader.py", line 83, in load_data
    for line in f.readlines():
  File "/scratch/user/phan3006/MATH689/dl_proj_summarun_py2.7/lib/python2.7/codecs.py", line 696, in readlines
    return self.reader.readlines(sizehint)
  File "/scratch/user/phan3006/MATH689/dl_proj_summarun_py2.7/lib/python2.7/codecs.py", line 605, in readlines
    data = self.read()
  File "/scratch/user/phan3006/MATH689/dl_proj_summarun_py2.7/lib/python2.7/codecs.py", line 494, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte
`

**Comment by pocheyeniu** [comment]
i will upload the data and w2v model tonight，so please pay attention to my project发自我的华为手机-------- 原始邮件 --------主题：[pocheyeniu/SummaRuNNer] How do I generate the labeled data? (#1)发件人：luhas123 收件人：pocheyeniu/SummaRuNNer 抄送：Subscribed I get this error when I run "train.py":
Traceback (most recent call last): File "train.py", line 133, in <module> train("model.0201") File "train.py", line 55, in train dr.load_data(FLAGS.train_data_file, max_doc_length, max_sen_length) File "/scratch/user/phan3006/MATH689/SummaRuNNer/data_reader.py", line 83, in load_data for line in f.readlines(): File "/scratch/user/phan3006/MATH689/dl_proj_summarun_py2.7/lib/python2.7/codecs.py", line 696, in readlines return self.reader.readlines(sizehint) File "/scratch/user/phan3006/MATH689/dl_proj_summarun_py2.7/lib/python2.7/codecs.py", line 605, in readlines data = self.read() File "/scratch/user/phan3006/MATH689/dl_proj_summarun_py2.7/lib/python2.7/codecs.py", line 494, in read newchars, decodedbytes = self.decode(data, self.errors) UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pocheyeniu/SummaRuNNer","title":"pocheyeniu/SummaRuNNer","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/pocheyeniu/SummaRuNNer"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"How do I generate the labeled data? (#1)"}],"action":{"name":"View Issue","url":"https://github.com/pocheyeniu/SummaRuNNer/issues/1"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pocheyeniu/SummaRuNNer/issues/1",
"url": "https://github.com/pocheyeniu/SummaRuNNer/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "How do I generate the labeled data? (#1)",
"sections": [
{
"text": "",
"activityTitle": "**luhas123**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@luhas123",
"facts": [
{
"name": "Repository: ",
"value": "pocheyeniu/SummaRuNNer"
},
{
"name": "Issue #: ",
"value": 1
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"pocheyeniu/SummaRuNNer\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"pocheyeniu/SummaRuNNer\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/pocheyeniu/SummaRuNNer/issues/1"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 393039758\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by pocheyeniu** [comment]
now the data & word2vec model are provided， you can have a try again.发自我的华为手机-------- 原始邮件 --------主题：[pocheyeniu/SummaRuNNer] How do I generate the labeled data? (#1)发件人：luhas123 收件人：pocheyeniu/SummaRuNNer 抄送：Subscribed I get this error when I run "train.py":
Traceback (most recent call last): File "train.py", line 133, in <module> train("model.0201") File "train.py", line 55, in train dr.load_data(FLAGS.train_data_file, max_doc_length, max_sen_length) File "/scratch/user/phan3006/MATH689/SummaRuNNer/data_reader.py", line 83, in load_data for line in f.readlines(): File "/scratch/user/phan3006/MATH689/dl_proj_summarun_py2.7/lib/python2.7/codecs.py", line 696, in readlines return self.reader.readlines(sizehint) File "/scratch/user/phan3006/MATH689/dl_proj_summarun_py2.7/lib/python2.7/codecs.py", line 605, in readlines data = self.read() File "/scratch/user/phan3006/MATH689/dl_proj_summarun_py2.7/lib/python2.7/codecs.py", line 494, in read newchars, decodedbytes = self.decode(data, self.errors) UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pocheyeniu/SummaRuNNer","title":"pocheyeniu/SummaRuNNer","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/pocheyeniu/SummaRuNNer"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"How do I generate the labeled data? (#1)"}],"action":{"name":"View Issue","url":"https://github.com/pocheyeniu/SummaRuNNer/issues/1"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pocheyeniu/SummaRuNNer/issues/1",
"url": "https://github.com/pocheyeniu/SummaRuNNer/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "How do I generate the labeled data? (#1)",
"sections": [
{
"text": "",
"activityTitle": "**luhas123**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@luhas123",
"facts": [
{
"name": "Repository: ",
"value": "pocheyeniu/SummaRuNNer"
},
{
"name": "Issue #: ",
"value": 1
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"pocheyeniu/SummaRuNNer\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"pocheyeniu/SummaRuNNer\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/pocheyeniu/SummaRuNNer/issues/1"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 393039758\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by odek53r** [comment]
Is the data download link unavailable now? I can't access to the data.

**Comment by pocheyeniu** [comment]
i will try it. it seems unaccessable except in china. i will upload it to google disk tonight.发自我的华为手机-------- 原始邮件 --------主题：Re: [pocheyeniu/SummaRuNNer] How do I generate the labeled data? (#1)发件人：Ci Jie 收件人：pocheyeniu/SummaRuNNer 抄送：zhaopeng ,State change Is the data download link unavailable now? I can't access to the data.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pocheyeniu/SummaRuNNer","title":"pocheyeniu/SummaRuNNer","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/pocheyeniu/SummaRuNNer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@odek53r in #1: Is the data download link unavailable now? I can't access to the data."}],"action":{"name":"View Issue","url":"https://github.com/pocheyeniu/SummaRuNNer/issues/1#issuecomment-434219712"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pocheyeniu/SummaRuNNer/issues/1#issuecomment-434219712",
"url": "https://github.com/pocheyeniu/SummaRuNNer/issues/1#issuecomment-434219712",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [pocheyeniu/SummaRuNNer] How do I generate the labeled data? (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Ci   Jie**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@odek53r",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"pocheyeniu/SummaRuNNer\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/pocheyeniu/SummaRuNNer/issues/1#issuecomment-434219712"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 393039758\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by odek53r** [comment]
Thanks.

**Comment by pocheyeniu** [comment]
ok now. if all thing is ok，give me a star: )发自我的华为手机-------- 原始邮件 --------主题：Re: [pocheyeniu/SummaRuNNer] How do I generate the labeled data? (#1)发件人：Ci Jie 收件人：pocheyeniu/SummaRuNNer 抄送：zhaopeng ,State change Thanks.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pocheyeniu/SummaRuNNer","title":"pocheyeniu/SummaRuNNer","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/pocheyeniu/SummaRuNNer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@odek53r in #1: Thanks."}],"action":{"name":"View Issue","url":"https://github.com/pocheyeniu/SummaRuNNer/issues/1#issuecomment-434571968"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pocheyeniu/SummaRuNNer/issues/1#issuecomment-434571968",
"url": "https://github.com/pocheyeniu/SummaRuNNer/issues/1#issuecomment-434571968",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [pocheyeniu/SummaRuNNer] How do I generate the labeled data? (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Ci   Jie**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@odek53r",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"pocheyeniu/SummaRuNNer\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/pocheyeniu/SummaRuNNer/issues/1#issuecomment-434571968"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 393039758\n}"
}
],
"themeColor": "26292E"
}
]
