### ISSUE TITLE
interpret summaRunner test output

### ISSUE THREAD

**Issue by r4sn4** [pocheyeniu/SummaRuNNer#2]
After testing outputs folder is created which contains two more folder hyp and ref. these two folders contain text files. What is difference in hyp and ref folder.
Does 1.txt tells sentence 1 summary and so on for other files?

**Comment by pocheyeniu** [comment]
when testing，u should pay attention to the files named "scores" and "index", they means the scores(higher means more important) of each setence and the indexs of doc. 发自我的华为手机-------- 原始邮件 --------主题：[pocheyeniu/SummaRuNNer] interpret summaRunner test output (#2)发件人：Rasna Tomar 收件人：pocheyeniu/SummaRuNNer 抄送：Subscribed After testing outputs folder is created which contains two more folder hyp and ref. these two folders contain text files. What is difference in hyp and ref folder.
Does 1.txt tells sentence 1 summary and so on for other files?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pocheyeniu/SummaRuNNer","title":"pocheyeniu/SummaRuNNer","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/pocheyeniu/SummaRuNNer"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"interpret summaRunner test output (#2)"}],"action":{"name":"View Issue","url":"https://github.com/pocheyeniu/SummaRuNNer/issues/2"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pocheyeniu/SummaRuNNer/issues/2",
"url": "https://github.com/pocheyeniu/SummaRuNNer/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "interpret summaRunner test output (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Rasna Tomar**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@r4sn4",
"facts": [
{
"name": "Repository: ",
"value": "pocheyeniu/SummaRuNNer"
},
{
"name": "Issue #: ",
"value": 2
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"pocheyeniu/SummaRuNNer\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"pocheyeniu/SummaRuNNer\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/pocheyeniu/SummaRuNNer/issues/2"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 412480183\n}"
}
],
"themeColor": "26292E"
}
]
