### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by Liguinan** [pocheyeniu/SummaRuNNer#3]
I use the data of CNN/Daily Mail and  the hyper parameter of the paper to train the model based on your project.  However, I found that the loss keeps almost constant when I set the batch size to 32 or 64 and if I set the batch size to 8, it will  be convergence gradually.  if you know the reasons, could you tell me about it , many thanks.

**Comment by pocheyeniu** [comment]
it seems  problems in your preprocess procedure， just debug it.发自我的华为手机-------- 原始邮件 --------主题：[pocheyeniu/SummaRuNNer] Training (#3)发件人：Liguinan 收件人：pocheyeniu/SummaRuNNer 抄送：Subscribed I use the data of CNN/Daily Mail and  the hyper parameter of the paper to train the model based on your project.  However, I found that the loss keeps almost constant when I set the batch size to 32 or 64 and if I set the batch size to 8, it will  be convergence gradually.  if you know the reasons, could you tell me about it , many thanks.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pocheyeniu/SummaRuNNer/issues/3?email_source=notifications\u0026email_token=AD6J45YDD7CBNP5SS5XIGWTP4MRDXA5CNFSM4H3PVPUKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G3XVXUA",
"url": "https://github.com/pocheyeniu/SummaRuNNer/issues/3?email_source=notifications\u0026email_token=AD6J45YDD7CBNP5SS5XIGWTP4MRDXA5CNFSM4H3PVPUKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G3XVXUA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Liguinan** [comment]
what do you mean？ the data format before reading or the data has been read before training？which step could be wrong if you know？ by the way，I preprocess the original data as your Chinese corpus in the project before reading it.  

many thanks for your kind help.

**Comment by pocheyeniu** [comment]
i have no idea. i suggest u debug it by yourself. i think it's not a hard work
